const mongoose = require('mongoose')

const userSchema = new mongoose.Schema({
  username:String,
  googleId:String,
  email:String,
  admin:Number,
  signupDate:Date,
  password:String,
  birthYear:Number,
  gender:String,
  mobile:String,
  address:String,
  city:String,
  isVerified:Boolean,
  emailToken:String,
  height:Number,
  weight:Number,
  bmi:Number,
  smoking:String,
  alcohol:String,
  bloodPresure:String,
  nutrition:String,
  stress:String,
  hoursExcercise:Number,
  sweets:String,
  foodSuplements:String,
  therapy:String,
  therapyComment:String,
  currentStatus:String,
  currentStatusComment:String,
  anamnesis:String,
  anamnesisComment:String,
  menstruation:String,
  regularMenstruation:String,
  regularGinecologyChecks:String,
  pregnancy:String,
  breastfeeding:String
})

module.exports = mongoose.model('User', userSchema)
